/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.myapp;

public final class R {
  public static final class mipmap {
    public static final int icon_72=0x7f010000;
  }
  public static final class style {
    public static final int AppTheme=0x7f020000;
  }
}